apiVersion: apps/v1
kind: Deployment
metadata:
  name: bg-core-deployment
  namespace: bg-dev
spec:
  selector:
    matchLabels:
      app: bg-core
  replicas: 1
  template:
    metadata:
      labels:
        app: bg-core
    spec:
      containers:
        - name: nginx
          image: 1gabriel/bg-core:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: mongodb.uri
              valueFrom:
                secretKeyRef:
                  key: mongodb.uri
                  name: bg-secret