apiVersion: v1
kind: Service
metadata:
  name: bg-authentication-service
  namespace: bg-dev
spec:
  type: NodePort
  selector:
    app: bg-authentication
  ports:
    - port: 8082
      targetPort: 8080
      nodePort: 30001