apiVersion: v1
kind: Service
metadata:
  name: bg-client-service
  namespace: bg-dev
spec:
  type: NodePort
  selector:
    app: bg-client
  ports:
    - port: 8081
      targetPort: 80
      nodePort: 30000